-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.

select
    prov_id as prov_id,
    TRIM(prov_nm) as provider_name,
    UPPER(TRIM(prov_spec_cd)) as provider_specialty_code,
    CAST(prov_active_flg AS BOOLEAN) as is_active,
    CAST(hire_dt AS DATE) as hire_date
from {{ source('staging', 'stg_providers') }}
