-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.

select
    txn_id as txn_id,
    enc_id as encounter_id,
    txn_amt as transaction_amount,
    CASE txn_st_cd WHEN 'P' THEN 'PAID' WHEN 'O' THEN 'OUTSTANDING' WHEN 'R' THEN 'REFUNDED' WHEN 'W' THEN 'WRITE_OFF' ELSE 'INVALID' END as transaction_status_code,
    CASE pmt_mthd_cd WHEN 'CC' THEN 'CREDIT_CARD' WHEN 'IN' THEN 'INVOICE' WHEN 'CA' THEN 'CASH' WHEN 'CH' THEN 'CHECK' ELSE 'UNKNOWN' END as payment_method_code,
    CAST(txn_dt AS TIMESTAMP) as transaction_timestamp
from {{ source('staging', 'stg_billing_transactions') }}
