-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.

select
    enc_id as enc_id,
    pat_id as patient_id,
    CAST(prov_id AS INTEGER) as provider_id,
    CAST(enc_dt AS TIMESTAMP) as encounter_timestamp,
    CASE enc_typ_cd WHEN 'TC' THEN 'TELEHEALTH' WHEN 'OV' THEN 'OFFICE_VISIT' WHEN 'IP' THEN 'INPATIENT' WHEN 'ER' THEN 'EMERGENCY' ELSE 'UNKNOWN' END as encounter_type_code,
    CAST(enc_amt AS DECIMAL(10,2)) as encounter_amount,
    CASE enc_st WHEN 'C' THEN 'COMPLETED' WHEN 'O' THEN 'OPEN' WHEN 'X' THEN 'CANCELLED' ELSE 'UNKNOWN' END as encounter_status
from {{ source('staging', 'stg_encounters') }}
