-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.

select
    plan_id as plan_id,
    TRIM(plan_nm) as plan_name,
    CASE plan_typ_cd WHEN 'H' THEN 'HMO' WHEN 'P' THEN 'PPO' WHEN 'M' THEN 'MEDICARE' ELSE 'OTHER' END as plan_type_code,
    CAST(plan_active AS BOOLEAN) as is_active
from {{ source('staging', 'stg_insurance_plans') }}
