-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.

select
    pat_id as pat_id,
    TRIM(pat_fname) as first_name,
    TRIM(pat_lname) as patient_last_name,
    CAST(dob AS DATE) as date_of_birth,
    ssn_enc as encrypted_ssn,
    CASE WHEN pat_st_cd IN ('A', 'D', 'S', 'I', 'Z') THEN pat_st_cd ELSE 'UNKNOWN' END as patient_status_code,
    plan_id as insurance_plan_id,
    CAST(created_ts AS TIMESTAMP) as created_at
from {{ source('staging', 'stg_patient_records') }}
