"""
generate_dbt_models.py

Reads artifacts/transformation_rules.json (the human-approved output of
rule_generator) and generates one dbt model per source table under
validation/dbt_models/models/marts/. Each model both renames columns AND
applies the value-level transformation logic (the CASE WHEN expressions
ai_mapper produced and a human reviewed/approved) -- this is the step that
turns "we documented what should happen to this column" into "this is what
actually happened to the data in Snowflake."

Run this AFTER a completed pipeline run (transformation_rules.json must
exist) and BEFORE `dbt run`:

    python validation/generate_dbt_models.py
    cd validation/dbt_models
    dbt run
    dbt test

Re-run this generator any time transformation_rules.json changes (e.g.
after redoing a human review with a corrected override) and re-run
`dbt run` to apply the update -- the generated .sql files are marked
auto-generated and should not be hand-edited, since the next run will
overwrite them.
"""
import json
import os
import sys
from collections import defaultdict

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import RULES_PATH  # noqa: E402

MODELS_DIR = os.path.join(os.path.dirname(__file__), "dbt_models", "models", "marts")

HEADER = """-- AUTO-GENERATED by validation/generate_dbt_models.py from
-- artifacts/transformation_rules.json -- do not hand-edit, it will be
-- overwritten the next time the generator runs.
--
-- Applies both the column rename AND the value-level transformation logic
-- for every AI-mapped, human-approved column in this table.
"""


def build_select_expr(rule: dict) -> str:
    source_col = rule["source_column"].split(".")[1]
    target_col = rule["target_column"]
    logic = rule["logic"]

    if logic == "IDENTITY" or logic.strip().lower() == source_col.lower():
        expr = source_col
    else:
        expr = logic

    return f"    {expr} as {target_col}"


def generate_model(table: str, rules: list[dict]) -> str:
    select_lines = ",\n".join(build_select_expr(r) for r in rules)
    return (
        f"{HEADER}\n"
        f"select\n"
        f"{select_lines}\n"
        f"from {{{{ source('staging', 'stg_{table}') }}}}\n"
    )


def main():
    if not os.path.exists(RULES_PATH):
        print(f"ERROR: {RULES_PATH} not found. Run the pipeline through rule_generator first.")
        sys.exit(1)

    with open(RULES_PATH) as f:
        rules = json.load(f)

    grouped = defaultdict(list)
    for rule in rules:
        table = rule["source_column"].split(".")[0]
        grouped[table].append(rule)

    os.makedirs(MODELS_DIR, exist_ok=True)

    for table, table_rules in grouped.items():
        model_sql = generate_model(table, table_rules)
        out_path = os.path.join(MODELS_DIR, f"transformed_{table}.sql")
        with open(out_path, "w") as f:
            f.write(model_sql)
        print(f"  wrote {out_path} ({len(table_rules)} columns)")

    print(f"\nGenerated {len(grouped)} dbt model(s) in {MODELS_DIR}")
    print("Next: cd validation/dbt_models && dbt run && dbt test")


if __name__ == "__main__":
    main()
